Repository jeonjw95/Invaders, pull requests merged in 2023-10, with the labels that each got.

#19 Fix: Add Bomb, SpeedUP Item & Modify Item Drop Probability
  src/engine/FileManager.java
  src/entity/EnemyShip.java
  src/entity/Item.java
  src/screen/GameScreen.java
Labels: feature

#23 fix: resolve release branch sound team behind commit
  .gitignore
  res/font.ttf
  src/engine/Core.java
  src/engine/SoundManager.java
Labels: bug

#26 Feature/twoplayer invincible
  res/graphics
  src/engine/DrawManager.java
  src/entity/Entity.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: feature

#21 feature/Speed
  src/entity/ItemQueue.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: feature

#28 Feature/random item
  src/engine/DrawManager.java
  src/entity/Item.java
  src/entity/ItemQueue.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: bug

#31 faster shooting item feature
  src/entity/Ship.java
Labels: feature

#35 Fix : monster slaying item issue
  src/screen/GameScreen.java
Labels: bug

#36 Feat : implementation of store item speed
  src/entity/Ship.java
Labels: feature

#37 Feature/additional life : create additional life item
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: bug, feature

#38 feat: apply currency team shop item
  src/screen/GameScreen.java
Labels: feature

#39 Hotfix/item acquire
  src/screen/GameScreen.java
Labels: bug

#40 Fix: 2p Player Item Acquire
  src/screen/GameScreen.java
Labels: bug

#44 Hotfix/timer bug
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: bug

#45 Hotfix/original speed
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: bug

#46 Fix: Dead Plane Item Store Bug
  src/screen/GameScreen.java
Labels: bug

#47 Hotfix/currency item
  src/entity/Ship.java
Labels: bug

#48 Fix: 1p-2p Item Acquire Simultaneously
  src/screen/GameScreen.java
Labels: bug
